### PR TITLE
Upgrade umbraco version & adding custom alias / enable list view support

### PR DESCRIPTION
**Pull request by aarym**
Updating uJet as this is a great code first solution with getting Umbraco & pure MVC solution to work using code first models. Adding alias support, version update and enable list view.

### CODE REVIEW

**Comment by logikfabrik** [comment]
Thanks for the PR! I'll look at it and merge it later tonight.

**Comment by logikfabrik** [comment]
The Umbraco upgrade looks good, and I like the idea of the Alias attribute! The uJet.nuspec file needs to be updated to reflect the new Umbraco version. Can you make that change as well?

I get why you renamed 'IsContainer' to 'EnableListView', but I think we should stick to how Umbraco has defined in code (even though the back office has another name for it). Just to be consistent; see AllowedAsRoot, Thumbnail, and so on. We could communicate that 'IsContainer' is to toggle list view in the property summary instead.

Just a side note; it would help if you made one PR for each change in the future. E.g. one for the upgrade, one for the addition of the Alias attribute, and one for the IsCointainer property. That way I can more easily go through and merge them seperately, and discussion of one PR won't hold up the other requests.

Thanks for contributing!

**Comment by aarym** [comment]
I will update the nuget spec file and yes I had this as separate checkins initially but then squashed them into single commit (work habit)

I will also change the EnableListView to IsContainer.

Regarding the uJet package. I would be keen to here your feedback on getting these added/fixed.
- Adding Folders for Document Types to have Parent for organising Document Types

- UIHint to be driven from the Umbraco.Core.Constants.PropertyEditors constants. 
Reason for this is the MediaPicker UIHint in uJet uses DefaultDataTypeDefinitionMapping.GetSupportedHints which expects the MediaPicker to be of type int but for the id 1035 for MediaPicker this is a string now in umbraco (uses MultipleMediaPicker). There was/is a legacy Umbraco.ContentPicker which was an int Data Type but this is not in the default install and being deprecated. So to get this working, the type is required to change to a string from int. It would be good if this was hooking into the property editor as this could then support the legacy Umbraco.MediaPicker.

- Macro Integration. Wonder if this is possible.

**Comment by logikfabrik** [comment]
- Regarding adding folders. I haven't tried the new version of Umbraco myself yet; is this something new? Your talking about a structure in the back office, not composition (inheritance) right? If you're talking about structure and Umbraco now supports it then I'm in. Would be great if uJet supported it too. Composition is already supported though.

- Changing how UIHint for MediaPicker targets int to string would be breaking change, so we need to be careful. If we add support for using Umbraco.Core.Constants.PropertyEditors, then we can make the change in that case. I'm not up-to-date with the latest changes to Umbraco, so I'm just guessing right now.

- uJet supports PreValues through the IDataType interface. Is that what you're thinking about?

Feel free to create issues for these things and pull requests. I'll go through and merge them as soon as I can.

**Pull request merged**
